# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OFMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', encrypted_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
