# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmuser',
            name='ofm_password',
            field=encrypted_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='ofmuser',
            name='ofm_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
