# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160619_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmuser',
            name='ofm_password',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofmuser',
            name='ofm_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
