# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(choices=[(1, 'Ägypten'), (2, 'Bosnien und Herzegowina'), (3, 'Brasilien'), (4, 'Deutschland'), (5, 'England'), (6, 'Frankreich'), (7, 'Italien'), (8, 'Kuba'), (9, 'Neuseeland'), (10, 'Norwegen'), (11, 'Österreich'), (12, 'San Marino'), (13, 'Spanien'), (14, 'Türkei'), (15, 'Thailand'), (16, 'Ukraine')])),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.IntegerField(choices=[(1, '1. Liga'), (2, '2. Liga'), (3, 'Regionalliga'), (4, 'Oberliga'), (5, 'Verbandsliga'), (6, 'Landesliga'), (7, 'Landesklasse'), (8, 'Bezirksliga'), (9, 'Bezirksklasse'), (10, 'Kreisliga'), (11, 'Kreisklasse')])),
                ('relay', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['season', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TW', 'Torwart'), ('LIB', 'Libero'), ('LV', 'Linker Verteidiger'), ('LMD', 'Linker Manndecker'), ('RMD', 'Rechter Manndecker'), ('RV', 'Rechter Verteidiger'), ('VS', 'Vorstopper'), ('LM', 'Linkes Mittelfeld'), ('DM', 'Defensives Mittelfeld'), ('ZM', 'Zentrales Mittelfeld'), ('RM', 'Rechtes Mittelfeld'), ('LS', 'Linker Stürmer'), ('MS', 'Mittelstürmer'), ('RS', 'Rechter Stürmer')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('awp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=1)),
                ('freshness', models.IntegerField(default=0)),
                ('games_in_season', models.IntegerField(default=0)),
                ('goals_in_season', models.IntegerField(default=0)),
                ('won_tacklings_in_season', models.IntegerField(default=0)),
                ('lost_tacklings_in_season', models.IntegerField(default=0)),
                ('won_friendly_tacklings_in_season', models.IntegerField(default=0)),
                ('lost_friendly_tacklings_in_season', models.IntegerField(default=0)),
                ('yellow_cards_in_season', models.IntegerField(default=0)),
                ('red_cards_in_season', models.IntegerField(default=0)),
                ('equity', models.IntegerField(default=0)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
            options={
                'verbose_name_plural': 'Player statistics',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='quarter',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='birthSeason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='playerstatistics',
            order_with_respect_to='player',
        ),
    ]
