# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='number',
        ),
    ]
