# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160604_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchday',
            old_name='matchday',
            new_name='number',
        ),
    ]
