# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchteamstatistics',
            name='strength',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
