# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160607_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TW', 'Torwart'), ('LIB', 'Libero'), ('LV', 'Linker Verteidiger'), ('LMD', 'Linker Manndecker'), ('RMD', 'Rechter Manndecker'), ('RV', 'Rechter Verteidiger'), ('VS', 'Vorstopper'), ('LM', 'Linkes Mittelfeld'), ('DM', 'Defensives Mittelfeld'), ('ZM', 'Zentrales Mittelfeld'), ('RM', 'Rechtes Mittelfeld'), ('LS', 'Linker Stürmer'), ('MS', 'Mittelstürmer'), ('RS', 'Rechter Stürmer')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('birthSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matchday')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('awp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=1)),
                ('freshness', models.IntegerField(default=0)),
                ('games_in_season', models.IntegerField(default=0)),
                ('goals_in_season', models.IntegerField(default=0)),
                ('won_tacklings_in_season', models.IntegerField(default=0)),
                ('lost_tacklings_in_season', models.IntegerField(default=0)),
                ('won_friendly_tacklings_in_season', models.IntegerField(default=0)),
                ('lost_friendly_tacklings_in_season', models.IntegerField(default=0)),
                ('yellow_cards_in_season', models.IntegerField(default=0)),
                ('red_cards_in_season', models.IntegerField(default=0)),
                ('equity', models.IntegerField(default=0)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='playerstatistics',
            order_with_respect_to='player',
        ),
    ]
