# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_checklist_checklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='to_be_checked_on_matchday',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='to_be_checked_on_matchdays',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
