# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160618_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matchday',
        ),
    ]
