# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161203_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
