# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20161203_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_chain_includes_player_statistics', models.BooleanField(default=True)),
                ('parsing_chain_includes_awp_boundaries', models.BooleanField(default=True)),
                ('parsing_chain_includes_finances', models.BooleanField(default=True)),
                ('parsing_chain_includes_matches', models.BooleanField(default=True)),
                ('parsing_chain_includes_match_details', models.BooleanField(default=False)),
                ('parsing_chain_includes_stadium_details', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
