# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_player_matchday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='playerstatistics',
            options={'verbose_name_plural': 'Player statistics'},
        ),
    ]
