# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160711_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
