# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160711_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='core.Matchday'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.Player'),
        ),
    ]
