# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170318_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingsetting',
            name='parsing_chain_includes_transfers',
            field=models.BooleanField(default=True),
        ),
    ]
