# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160711_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstatistics',
            options={'ordering': ['player', '-matchday'], 'verbose_name_plural': 'Player statistics'},
        ),
    ]
