# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20160716_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('income_visitors_league', models.IntegerField(default=0)),
                ('income_sponsoring', models.IntegerField(default=0)),
                ('income_cup', models.IntegerField(default=0)),
                ('income_interests', models.IntegerField(default=0)),
                ('income_loan', models.IntegerField(default=0)),
                ('income_transfer', models.IntegerField(default=0)),
                ('income_visitors_friendlies', models.IntegerField(default=0)),
                ('income_friendlies', models.IntegerField(default=0)),
                ('income_funcup', models.IntegerField(default=0)),
                ('income_betting', models.IntegerField(default=0)),
                ('expenses_player_salaries', models.IntegerField(default=0)),
                ('expenses_stadium', models.IntegerField(default=0)),
                ('expenses_youth', models.IntegerField(default=0)),
                ('expenses_interests', models.IntegerField(default=0)),
                ('expenses_trainings', models.IntegerField(default=0)),
                ('expenses_transfer', models.IntegerField(default=0)),
                ('expenses_compensation', models.IntegerField(default=0)),
                ('expenses_friendlies', models.IntegerField(default=0)),
                ('expenses_funcup', models.IntegerField(default=0)),
                ('expenses_betting', models.IntegerField(default=0)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matchday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-matchday'],
            },
        ),
    ]
