# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_finance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finance',
            unique_together=set([('user', 'matchday')]),
        ),
    ]
