# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160717_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='core.Matchday'),
        ),
    ]
