# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20160730_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('L', 'Liga'), ('F', 'Friendly'), ('P', 'Pokal'), ('F', 'Fun-Cup')], max_length=1)),
                ('venue', models.CharField(max_length=200)),
                ('home_team', models.CharField(max_length=200)),
                ('guest_team', models.CharField(max_length=200)),
                ('home_goals', models.IntegerField(default=0)),
                ('guest_goals', models.IntegerField(default=0)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matchday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-matchday'],
            },
        ),
        migrations.CreateModel(
            name='MatchStadiumStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_statistics', to='core.Match')),
            ],
            options={
                'ordering': ['match'],
            },
        ),
        migrations.CreateModel(
            name='StadiumStandStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('N', 'Nord'), ('S', 'Süd'), ('W', 'West'), ('O', 'Ost')], max_length=1)),
                ('capacity', models.IntegerField(default=0)),
                ('visitors', models.IntegerField(default=0)),
                ('ticket_price', models.IntegerField(default=0)),
                ('condition', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stadium_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_statistics', to='core.MatchStadiumStatistics')),
            ],
        ),
    ]
