# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_match_matchstadiumstatistics_stadiumstandstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('L', 'Liga'), ('F', 'Friendly'), ('P', 'Pokal'), ('F', 'Fun-Cup')], default='L', max_length=1),
        ),
    ]
