# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160807_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['user', '-matchday'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchstadiumstatistics',
            options={'ordering': ['match'], 'verbose_name_plural': 'Match stadium statistics'},
        ),
        migrations.AlterModelOptions(
            name='stadiumstandstatistics',
            options={'verbose_name_plural': 'Stadium stand statistics'},
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.Matchday'),
        ),
    ]
