# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160808_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_home_match',
            field=models.BooleanField(default=True),
        ),
    ]
