# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_match_is_home_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_home_match',
            field=models.BooleanField(),
        ),
    ]
