# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160821_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwpBoundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awp_boundaries', to='core.Matchday')),
            ],
            options={
                'verbose_name_plural': 'AWP Boundaries',
                'ordering': ['-matchday'],
            },
        ),
        migrations.CreateModel(
            name='AwpBoundariesKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(db_index=True)),
                ('value', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AwpBoundaries')),
            ],
        ),
    ]
