# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dictionary_keyvaluepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluepair',
            name='key',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='keyvaluepair',
            name='value',
            field=models.IntegerField(),
        ),
    ]
