# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20161003_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awpboundaries',
            options={'ordering': ['-name'], 'verbose_name_plural': 'AWP Boundaries'},
        ),
        migrations.RemoveField(
            model_name='awpboundaries',
            name='matchday',
        ),
    ]
