# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('awp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=17)),
                ('strength', models.IntegerField(default=1)),
                ('freshness', models.IntegerField(default=1)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonedPlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('won_tacklings', models.IntegerField(default=0)),
                ('lost_tacklings', models.IntegerField(default=0)),
                ('won_friendly_tacklings', models.IntegerField(default=0)),
                ('lost_friendly_tacklings', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_statistics.Player')),
            ],
        ),
        migrations.AddField(
            model_name='dailyplayerstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_statistics.Player'),
        ),
    ]
