# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='birth',
            new_name='birthSeason',
        ),
    ]
