
LOGIN = 'http://v7.www.onlinefussballmanager.de'
HEAD = 'http://v7.www.onlinefussballmanager.de/head-int.php'
OFFICE = 'http://v7.www.onlinefussballmanager.de/office/_frame_buero.php'
TEAM = 'http://v7.www.onlinefussballmanager.de/team/_frame_mannschaft.php'
TRANSFER = 'http://v7.www.onlinefussballmanager.de/transfer/_frame_transfer.php'
STADIUM = 'http://v7.www.onlinefussballmanager.de/stadium/_frame_stadion.php'
FINANCES = 'http://v7.www.onlinefussballmanager.de/finances/_frame_finanzen.php'
LEAGUE = 'http://v7.www.onlinefussballmanager.de/league/_frame_liga.php'
OFM_CUP = 'http://v7.www.onlinefussballmanager.de/ofm_cup/_frame_pokal.php'
WORLD_CUP = 'http://v7.www.onlinefussballmanager.de/world_cup/_frame_worldcup.php'
FUN_CUP = 'http://v7.www.onlinefussballmanager.de/funcups/_frame_funcup.php'
FRIENDLIES = 'http://v7.www.onlinefussballmanager.de/friendlies/_frame_freund.php'
STATISTICS = 'http://v7.www.onlinefussballmanager.de/statistics/_frame_statistiken.php'
